### ISSUE TITLE
ToneExample not working

### ISSUE THREAD

**Issue by egueli** [madhephaestus/ESP32Servo#10]
I'm trying to use the `tone()` function provided by ESP32Servo. But when running `ToneExample`, I see no output. The pin is always at low state.

- I tried this on two ESP32s, one is an ESP32+OLED module.
- The classic Arduino Blink example does make the pin go high and low.
- The `PWMExample` does work on the same pin, i.e. there are PWM changes.

**Comment by madhephaestus** [comment]
Issue should be resolved as of 0.6.3
