### ISSUE TITLE
2 compile errors

### ISSUE THREAD

**Issue by VenturaGZAAA** [madhephaestus/ESP32Servo#57]
When trying to compile using PlatformIO in VSCode I get:

error at line 312 of ESP32PWM.cpp:
   "void value not ignored as it ought to be"

first there was two errors, the other one saying something similar to:
  can not return a 'void' value to a 'bool' type value
but VSCode sugesteted I could turn on some error ignoring thingy and I pressed on that, althought I keep getting the other error.

Sorry in advance for the terrible description.

**Comment by VenturaGZAAA** [comment]
[abstractBoyd](https://github.com/abstractBoyd) provided much better documentation on this issue.

**Comment by madhephaestus** [comment]
Duplicate
