### ISSUE TITLE
ESP32 SERVO LIBRARY LED PIN ERROR

### ISSUE THREAD

**Issue by Radiance-20** [madhephaestus/ESP32Servo#63]
ESP32 servo library comes up with led  issues when verified on the Arduino IDE. This makes it not to be used for any project intended.
ESP32  board version is 3.0.0
ESP32 Servo library version is 1.2.1
Arduino IDE versionis 2.3.2

**Comment by madhephaestus** [comment]
if you are using the 3.x.x toolchain you must use the 3.0.5 or greater release of this library.

**Comment by Radiance-20** [comment]
Thank you for your response sir.

**Comment by madhephaestus** [comment]
Of course! If that didn't fix your issue the feel free to reopen the ticket
if this solution doesn't work for you.
