### ISSUE TITLE
Disable, or support configurable, Debug output

### ISSUE THREAD

**Issue by WayneKeenan** [madhephaestus/ESP32Servo#8]
Generally it's a good practice that libraries shouldn't output debug, unless requested by user/client code or some kind of other logging settings, as it can interfere with the normal operation of a program.

Please could you remove, or make it a runtime flag to enable/disable (default: disabled), all debug output?  e.g. I'm seeing this:
 
```
PWM on ledc channel #1 using 'timer 0' to freq 50.00Hz
```
Thanks

**Comment by madhephaestus** [comment]
fair point

**Comment by madhephaestus** [comment]
0.6.2 is released with this change
